// <auto-generated />
namespace LittleSurvey.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OfferedAnswers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OfferedAnswers));
        
        string IMigrationMetadata.Id
        {
            get { return "201708031508411_OfferedAnswers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
